# Generated by Django 2.2.6 on 2019-10-16 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191016_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Ad Soyad')),
                ('comment_content', models.CharField(max_length=200, verbose_name='Şərh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.Article', verbose_name='Məqalə')),
            ],
        ),
    ]
